### ISSUE TITLE
Create a unified, extendable interface for serialisers

### ISSUE THREAD

**Issue by dmitrii-doronin** [bhftbootcamp/Serde.jl#23]
### Description
At present, the interface functions like ‘ignore_field’, ‘ignore_null’, and others are not mandatory for serialisers. The package should be reorganized to enable the extension of these functions by each serialisation module and to establish a default action.

### Tasks

- [ ]  Design a User-Friendly Interface and Package Structure. The goal is to create an intuitive and easy-to-navigate system.
- [ ]  Create a comprehensive test suite, focusing on the feature’s backwards compatibility and functionality.
- [ ]  Revise the documentation to Include detailed information about changes to structure and currently implemented functions for packages.
